### ISSUE TITLE
Error while running 'make all'

### ISSUE THREAD

**Issue by boye** [vechain/thor#125] opened 2018-08-26 18:26 UTC
Hi there,

I am getting an error when trying to build a new binary after pulling all recent changes from Github.

## OS Version: 
Linux CentOS 7
 
## Expected behavior
Building should be successful and a new binary should be created in the bin directory.

## Actual behavior
I am getting the following error: 
```
Building thor...
github.com/vechain/thor/cmd/thor
# github.com/vechain/thor/cmd/thor
cmd/thor/main.go:178:25: too many arguments in call to solo.New
	have (*chain.Chain, *state.Creator, *logdb.LogDB, *txpool.TxPool, uint64, bool)
	want (*chain.Chain, *state.Creator, *logdb.LogDB, *txpool.TxPool, bool)
make: *** [thor] Error 2
```

## Steps to reproduce the behavior
Try to run `make all` after pulling all recent Git changes from master

**Comment by libotony** [comment] 2018-08-27 03:08
Duplicate of #118, update the code and run `make dep` will help

**Closed** 2018-08-29 12:50 UTC
